version: "3"

#Define stack network
networks:
  wraithnet:
    driver: bridge

#Define stack services
services: 
  #Main application container
  sms:
    image: sms:v1
    container_name: wraith_sms
    hostname: wraith_sms
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./dockerfiles/wraithapp.Dockerfile
    depends_on:
      - mongodb
      - redis
      - amqp
    environment:
      - SRV_BIND_ADDR=0.0.0.0
      - MGO_CONN_STR=mongodb://mongodb:27017
      - RED_HOST=redis
      - EMAIL_ENABLED=false
      - AMQP_HOST=amqp
      - AMQP_USERNAME=guest
      - AMQP_PASSWORD=guest
      - CLI_BASE_URL=http://localhost:8080
      - SRV_BASE_URL=http://localhost:8888/api
    networks:
      - wraithnet
    ports:
      - "8888:8888"
    volumes:
      - ./message_server:/wraith_sms
    #user: "${UID:-1000}:${GID:-1000}"  # Default to 1000 if not set

  #MongoDB database container
  mongodb:
    image: bitnami/mongodb:latest
    container_name: wraith_mdb
    hostname: wraith_mdb
    restart: unless-stopped
    attach: false
    networks:
      - wraithnet
    ports:
      - "27018:27017"

  #Redis database container
  redis:
    image: redis:latest
    container_name: wraith_rdb
    hostname: wraith_rdb
    restart: unless-stopped
    attach: false
    networks:
      - wraithnet
    ports:
      - "6380:6379"

  #LavinMQ message broker
  amqp:
    image: cloudamqp/lavinmq:latest
    container_name: wraith_amqp
    hostname: wraith_amqp
    restart: unless-stopped
    attach: false
    networks:
      - wraithnet
    ports:
      - "5673:5672"
      - "15673:15672"