root = "."
tmp_dir = "tmp"

[build]
	cmd = "make build"
	bin = "./tmp/sms_server"
	main = "main/main.go"
	delay = 1000
	exclude_dir = ["assets", "tmp", "vendor"]
	include_ext = ["go", "tpl", "tmpl", "html"]
	exclude_regex = ["_test\\.go"]

[log]
	time = true  # Set this to true to show log time