root = "."
tmp_dir = "tmp"

[build]
	cmd = "make cleanbin && make build"
	#cmd = "go build -ldflags \"-s -w\" -o tmp/sms_server main/main.go"
	bin = "./tmp/sms_server"
	main = "main/main.go"
	delay = 1000
	exclude_dir = ["assets", "tmp", "vendor"]
	include_ext = ["go", "tpl", "tmpl", "html"]
	exclude_regex = ["_test\\.go"]
	stop_on_error = true

[log]
	time = true  # Set this to true to show log time