#!/usr/bin/env python3
# Python http.server that sets Access-Control-Allow-Origin header.
# https://gist.github.com/razor-x/9542707

import os
import sys
import http.server
import socketserver

DEFAULT_PORT = 8080

class HTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
	def end_headers(self):
		self.send_header("Access-Control-Allow-Origin", "*")
		http.server.SimpleHTTPRequestHandler.end_headers(self)

def server(port):
	httpd = socketserver.TCPServer(("127.0.0.1", port), HTTPRequestHandler)
	return httpd

if __name__ == "__main__":
	#Attempt to get a different port from the user at `argv[1]`
	port = DEFAULT_PORT
	if len(sys.argv) == 2 and sys.argv[1].isdigit():
		port = int(sys.argv[1])
	else:
		print(f"Using default port {DEFAULT_PORT}")

	#Start the server
	httpd = server(port)
	try:
		print(f"Serving from ./ at localhost:{port}")
		httpd.serve_forever()
	except KeyboardInterrupt:
		print("...Shutting down http server")
		httpd.shutdown()
		sys.exit()
