package tests

import (
	"encoding/hex"
	"fmt"
	"testing"

	"wraith.me/clientside_crypto/crypto"
)

func TestEd25519Keygen(t *testing.T) {
	//Generate a keypair
	kp := crypto.Ed25519Keygen()

	//Print stuff
	fmt.Printf("SK: %s\n", hex.EncodeToString(kp.SK[:]))
	fmt.Printf("PK: %s\n", hex.EncodeToString(kp.PK[:]))
	fmt.Printf("FP: %s\n", kp.Fingerprint)

	//JSON
	json := kp.JSON()
	obj, err := crypto.Ed25519FromJSON(json)
	if err != nil {
		t.Fatal(err)
	}
	fmt.Printf("JSON: %s\n", json)
	fmt.Printf("Obj: %s\n", obj)

	//Attempt to parse from a JSON string; generated by `simple_vault::Vault.kstore.toString()`
	jsons := `{"sk":"eK7Rv8dfHPrWgeVcHIoskqMNke2EjWUFaIgafCaU3ZE=","pk":"wDw04q6c94g7zn5IwGe1M0E6NJRDuHCa0x+joia8DFg="}`
	obj2, err := crypto.Ed25519FromJSON(jsons)
	if err != nil {
		t.Fatal(err)
	}
	fmt.Printf("Obj2: %s\n", obj2)
}
